#cloud-config
package_upgrade: true

packages:
    - docker.io
    - docker-compose
    - azure-cli
    #- powershell not supported on 20.04 (2020-07-20)

# create the docker group
groups:
    - docker

# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: mydefaultuser
      groups: docker
